version: '3.7'

services:
  workspace:
    volumes:
      - ${BACKEND_PATH_HOST}:/var/www/backend
      - ${FRONTEND_PATH_HOST}:/var/www/frontend
      - ${PHP_PATH_HOST}/local.ini:/usr/local/etc/php/conf.d/local.ini
    build:
      context: ./
      dockerfile: ${PHP_PATH_HOST}/Dockerfile
    ports:
      - "8085:8080"
    user: 1000:1000 # Без этого контейнер как root запускается
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: black_list
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    tty: true
    restart: unless-stopped
    volumes:
      - ${BACKEND_PATH_HOST}:/var/www/backend/
      - ${FRONTEND_PATH_HOST}:/var/www/frontend/
      - ${NGINX_PATH_HOST}/conf.d/:/etc/nginx/conf.d/
      - ${NGINX_PATH_HOST}/log/:/var/log/nginx/
    ports:
      - ${WEB_HTTP_PORT}:80
    depends_on:
      - workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
